name: YouTube Live Stream Watcher

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "* */6 * * *"  # 6시간마다 실행

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv

    - name: Debug environment variables
      run: |
        echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}"
        echo "YOUTUBE_CHANNEL_ID=${{ secrets.YOUTUBE_CHANNEL_ID }}"

    - name: Run script to update README
      run: python uzuhama_live_link.py

    - name: Check if readme.md was updated
      run: git status

    - name: Configure Git
      run: |
        git config --local user.email "eun2ce@github.com"
        git config --local user.name "eun2ce"

    - name: Commit updated readme
      run: |
        git add .
        git commit -m "docs: ${COMMIT_DATE} 실방 링크 추가" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
