name: YouTube Live Stream Watcher

on:
  schedule:
    - cron: '*/5 * * * *'  # 5분마다 실행 (원하는 주기로 수정 가능)
  workflow_dispatch:  # 수동으로 실행 가능

jobs:
  update-live-link:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run YouTube Live Check and Update Markdown
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}
        run: |
          python uzuhama_live_link.py

      - name: Set up GitHub Token for authentication
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "eun2ce"
          git config --global user.email "eun2ce@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

      - name: Check status and add changes
        run: |
          git status
          git add readme.md
          git diff --quiet || git commit -m "Update live stream URL"
          git push
