name: YouTube Live Stream Watcher

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # - cron: "0 0 */1 * *" # 매일
    - cron: "*/1 * * * *" # 1분마다

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run script to update README
      run: |
        python uzuhama_live_link.py
    - name: Check if README was updated
      run: |
        git status
    - name: Commit updated README
      run: |
        git add readme.md
        git diff  # 확인용, 실제로 변경 사항이 있다면 표시됩니다
        git config --local user.email "eun2ce@github.com"
        git config --local user.name "eun2ce"
        git commit -m "docs: 새로운 실시간 방송 링크 추가" || echo "No changes to commit"
        git push
