name: Update README

on:
  push:
    paths:
      - 'readme-*.md'   # readme-YYYY.md가 수정될 때만
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README.md
        run: |
          echo "# 목차" > README.md
          for readme in readme-*.md; do
            [ -f "$readme" ] && echo "- [$readme]($readme)" >> README.md
          done

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "chore: update README index" || echo "No changes"
          git push
