name: YouTube Live Stream Watcher

on:
  schedule:
    - cron: "0 */6 * * *"   # 6시간마다
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run script to update readmes
        run: python uzuhama_live_link.py

      - name: Configure Git
        run: |
          git config user.email "eun2ce@users.noreply.github.com"
          git config user.name "eun2ce"

      - name: Commit updated files
        run: |
          COMMIT_DATE="$(date +'%Y-%m-%d %H:%M:%S %Z')"
          git add .
          git commit -m "docs: ${COMMIT_DATE} 실방 링크 추가" || echo "No changes to commit"
          git push
